name: Functions - Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'squad-func/**'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'sfuncrunners'   
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './squad-func/'       
  DOTNET_VERSION: '10.0.x'                   

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v6

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: echo package path
      run: echo ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: bash
      run: |
        dotnet build --configuration Release --output ./output
        
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        sku: 'flexconsumption'
        remote-build: false
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        scm-do-build-during-deployment: false
        enable-oryx-build: false